name: Publish NuGet Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and package each project
        run: |
          echo "Building and packing .csproj files..."
          for project in $(find . -type f -name '*.csproj'); do
            echo "Processing project: $project"
            dotnet build --configuration Release --no-restore "$project"
            dotnet pack --configuration Release --no-build --output ./nupkg "$project"
          done

      - name: Publish NuGet packages
        run: |
          if [ -d "./nupkg" ]; then
            for package in $(find ./nupkg -name '*.nupkg'); do
              echo "Publishing package: $package"
              dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
            done
          else
            echo "No packages to publish."
          fi
