name: Publish NuGet Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get modified .csproj files
        id: get-changes
        run: |
          echo -e "\033[36mFetching modified .csproj files in all commits from the current push...\033[0m"

          # Fetch full history to ensure valid references
          git fetch --prune --unshallow || true
          git fetch origin master --depth=2 || true

          # Get the list of commit SHAs in this push
          PREVIOUS_SHA=${{ github.event.before }}
          if [ -z "$PREVIOUS_SHA" ] || ! git rev-parse "$PREVIOUS_SHA" >/dev/null 2>&1; then
            PREVIOUS_SHA=$(git rev-list -n 1 HEAD~1)
          fi
          echo -e "\033[36mCommits in the push:\033[0m"
          COMMITS=$(git rev-list $PREVIOUS_SHA..${{ github.sha }})
          echo "$COMMITS"

          # Remove duplicates and output modified projects
          MODIFIED_PROJECTS=$(git diff --name-only $PREVIOUS_SHA..${{ github.sha }} | grep '\.csproj$' | sort | uniq || true)
          if [ -z "${MODIFIED_PROJECTS}" ]; then
            echo -e "\033[33mNo modified .csproj files found in the latest push.\033[0m"
          else
            echo -e "\033[36mModified projects:\033[0m"
            echo "$MODIFIED_PROJECTS"
          fi
          MODIFIED_PROJECTS=$(echo "$MODIFIED_PROJECTS" | tr '\n' ',' | sed 's/,$//')
          echo "MODIFIED_PROJECTS=$MODIFIED_PROJECTS" >> $GITHUB_ENV

      - name: Setup .NET
        if: env.MODIFIED_PROJECTS != ''
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        if: env.MODIFIED_PROJECTS != ''
        run: dotnet restore

      - name: Build and pack modified projects
        if: env.MODIFIED_PROJECTS != ''
        run: |
          echo -e "\033[36mProcessing modified .csproj files...\033[0m"
          MODIFIED_PROJECTS=$(echo ${{ env.MODIFIED_PROJECTS }} | tr ',' '\n')
          for project in $MODIFIED_PROJECTS; do
            echo -e "\033[35mBuilding and packing project: $project\033[0m"
            dotnet build --configuration Release --no-restore "$project" || {
              warning "Error occurred while building $project. Check logs for details."
            }
            dotnet pack --configuration Release --no-build --output ./nupkg $project || {
              warning "Error occurred while packing $project. Check logs for details."
            }
          done

      - name: Publish packages
        if: env.MODIFIED_PROJECTS != ''
        run: |
          echo -e "\033[36mPublishing .nupkg files...\033[0m"
          for package in $(find ./nupkg -name '*.nupkg'); do
            echo -e "\033[35mPublishing file $package...\033[0m"
            dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate || {
              warning "Error occurred while publishing $package. Check logs for details."
            }
          done
