name: Publish NuGet Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get modified .csproj files
        run: |
          chmod +x .github/scripts/get_modified_files.sh
          .github/scripts/get_modified_files.sh '${{ toJson(github.event.commits) }}' '${{ github.ref_name }}' '.csproj'

      - name: Setup .NET
        if: env.MODIFIED_PROJECTS != ''
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build and pack modified projects
        if: env.MODIFIED_PROJECTS != ''
        run: |
          # Builds and packs all modified projects.
          echo -e "\033[36mProcessing modified .csproj files...\033[0m"
          FAILED_PROJECTS=""
          MODIFIED_PROJECTS=$(echo ${{ env.MODIFIED_PROJECTS }} | tr ',' '\n')
          for project in $MODIFIED_PROJECTS; do
            echo -e "\033[35mBuilding and packing project: $project\033[0m"
            if dotnet pack --configuration Release --output ./nupkg $project; then
              echo -e "\033[32mProject $project packed successfully.\033[0m"
            else
              FAILED_PROJECTS="$FAILED_PROJECTS$project,"
            fi
          done
          echo "FAILED_PROJECTS=$FAILED_PROJECTS" >> $GITHUB_ENV

      - name: Publish packages
        if: env.MODIFIED_PROJECTS != ''
        run: |
          # Publishes all built packages.
          echo -e "\033[36mPublishing generated .nupkg files...\033[0m"
          FAILED_PROJECTS=$(echo ${{ env.FAILED_PROJECTS }})
          for package in $(find ./nupkg -name '*.nupkg'); do
            echo -e "\033[35mPublishing file $package...\033[0m"
            if dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate; then
              echo -e "\033[32mPackage $package published successfully.\033[0m"
            else
              FAILED_PROJECTS="$FAILED_PROJECTS$package,"
            fi
          done
          echo "FAILED_PROJECTS=$FAILED_PROJECTS" >> $GITHUB_ENV

      - name: Output failure
        if: env.FAILED_PROJECTS != ''
        run: |
          # Outputs all failed projects in the console and fails the process.
          FAILED_PROJECTS=$(echo ${{ env.FAILED_PROJECTS }} | sed 's/,$//')
          echo "::error::The following projects failed to pack/publish: $FAILED_PROJECTS"
          exit 1
