name: Publish NuGet Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get modified .csproj files
        id: get-changes
        run: |
          echo "Fetching modified .csproj files..."
          PREVIOUS_SHA=${{ github.event.before }}
          if [ -z "$PREVIOUS_SHA" ]; then
            PREVIOUS_SHA=$(git rev-parse HEAD~1)
          fi
          MODIFIED_PROJECTS=$(git diff --name-only $PREVIOUS_SHA ${{ github.sha }} | grep '\.csproj$' || true)
          echo "Modified projects:"
          echo "$MODIFIED_PROJECTS"
          echo "$MODIFIED_PROJECTS" >> $GITHUB_ENV
          
      - name: Checkout code
        if: env.MODIFIED_PROJECTS != ''
        uses: actions/checkout@v3

      - name: Setup .NET
        if: env.MODIFIED_PROJECTS != ''
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        if: env.MODIFIED_PROJECTS != ''
        run: dotnet restore

      - name: Build and publish modified projects
        if: env.MODIFIED_PROJECTS != ''
        run: |
          echo "Processing modified .csproj files..."
          for project in ${{ steps.get-changes.outputs.projects }}; do
            echo "Building and packing project: $project"
            dotnet build --configuration Release --no-restore "$project"
            
            PACKAGE_PATH=$(find "$(dirname "$project")/bin/Release" -name '*.nupkg')
            for package in $PACKAGE_PATH; do
              echo "Attempting to publish package: $package"
              dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate || {
                echo "Error occurred while publishing $package. Check logs for details."
              }
            done
          done

      - name: No changes detected
        if: env.MODIFIED_PROJECTS == ''
        run: echo "No modified .csproj files found in the latest push."
